# Generated by Django 4.2.1 on 2023-05-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='image/Untitled1.jpg', upload_to='image/')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('inventory', models.BooleanField(default=False)),
            ],
        ),
    ]
