# Generated by Django 4.2.1 on 2023-05-14 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2023, 5, 14, 13, 1, 15, 944208)),
        ),
    ]
